description: Default simulation scenario
end_time: '2025-06-11T17:40:02.578056'
market:
  initial_price: 50000.0
  liquidity_profile:
    depth: 2000
    spread: 0.001
  market_depth: 1000000.0
  trading_activity:
    base_volume: 2000
    volume_volatility: 0.3
  volatility: 0.02
name: default
network:
  base_hashrate: 100.0
  block_time: 600
  consensus_type: PoW
  difficulty: 1000000.0
  min_stake: 0.0
  network_growth:
    growth_rate: 0.15
    volatility: 0.1
  num_miners: 1000
random_seed: null
start_time: '2025-05-12T17:40:02.578056'
time_step: !!python/object/apply:datetime.timedelta
- 0
- 3600
- 0
